### ISSUE TITLE
thanks for not mentioning me.

### ISSUE THREAD

**Issue by Ladvace** [bue221/astro-portfolio#2]
I know that the project is open source and you are free to use it, but what's the point of posting a 1:1 copy of my template on the astro community without mentioning me?

**Comment by bue221** [comment]
It's not a direct copy, but I did draw inspiration from your portfolio and many others. I took various ideas and combined them, adding more common technologies, etc. However, you're right. I will add a section crediting the portfolios that inspired me. Thank you for your feedback!
